apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./application-controller
- ./config
- ./dex
- ./repo-server
- ./server
- ./redis

images:
- name: argoproj/argocd
  newName: argoproj/argocd
  newTag: v1.6.1
