---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
  labels:
    app.kubernetes.io/name: argocd-dex-server
    helm.sh/chart: argo-cd-2.6.0
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/version: v2.22.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
      app.kubernetes.io/instance: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-dex-server
        helm.sh/chart: argo-cd-2.6.0
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/component: dex-server
        app.kubernetes.io/version: v2.22.0
    spec:
      initContainers:
      - name: copyutil
        image: argoproj/argocd:v1.6.2
        imagePullPolicy: IfNotPresent
        resources:
          {}
        command:
        - cp
        - /usr/local/bin/argocd-util
        - /shared
        volumeMounts:
        - mountPath: /shared
          name: static-files
      containers:
      - name: dex-server
        image: quay.io/dexidp/dex:v2.22.0
        imagePullPolicy: IfNotPresent
        command:
        - /shared/argocd-util
        - rundex
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        - name: grpc
          containerPort: 5557
          protocol: TCP
        volumeMounts:
          - mountPath: /shared
            name: static-files
        resources:
          {}
      serviceAccountName: argocd-dex-server
      volumes:
        - emptyDir: {}
          name: static-files
---
