apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - /base

patchesStrategicMerge:
  - overlays/argocd-server-service.yaml

images:
- name: argoproj/argocd
  newTag: v1.6.2
