apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj/argo-cd/manifests/cluster-install

namespace: argocd

images:
- name: argoproj/argocd
  newName: docker.pkg.github.com/argoproj/argo-cd/argocd
  newTag: 1.7.0-ba71ad93
